# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec78ed0cc6710598f96d0a44af3f71adbd80089f189564067738b7926255a19492fda1683e9111e9316896e454f8a94173d18ed5985825de32889cffef0fe7c1

test:
  secret_key_base: 661ecee58cf3c88d3e3e03240eb260276d9f93016acf6842aa23c2c3bfa5bf7c890d89c8ff33d7c8f27644088bd2e1e489761ece5ad9f004530025b519bbfdeb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
